### ISSUE TITLE
Répartition

### ISSUE THREAD

**Issue by QuentinRiv** [Olius/tour#1]
Du coup... Concernant la liste des trucs à apporter, chacun prend un peu tout de son coté, ou on essaye de répartir entre nous ce qu'on peut répartir  ?
༼ つ ◕_◕ ༽つ

**Comment by Olius** [comment]
C'est une bonne question, quelqu'un a eu la bonne idée de mettre des noms après le stuff.  D'ailleurs tu prends ta tente aussi ?

**Comment by QuentinRiv** [comment]
si la tienne est une à 3 places, et que Laurent/Ausra veulent dormir à la belle étoile, du coup, non.
mais si y a besoin, alors je dois pouvoir en prendre une à 2 places (faut juste vite me dire)
et sinon, tu pourrais toujours mettre une partie de la tente dans mon sac (genre les sardines, ...)

**Comment by Olius** [comment]
Je crois que nous avons résolu ce problème.
